version: "3.9"  # optional since v1.27.0
services:
  drupal:
    image: drupal:8.9.13
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
    volumes:
      - ./contrib:/opt/drupal/web/modules/contrib
      - ./modules:/opt/drupal/web/modules/custom
      - sites_default:/opt/drupal/web/sites/default
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  drupal_root:
  sites_default:
  db_volume:

